/** Captured 2026-09-20 from https://www.stonkfun.xyz/api/public/v1. Not live data. */

export const FIXTURE_RETRIEVED_AT = "2026-09-20T18:59:13.462Z";
export const FIXTURE_SOURCE = "https://www.stonkfun.xyz/api/public/v1";

export const FIXTURE_STATS = {
  network: "mainnet-beta",
  tokens: {
    poolsAvailable: true,
    total: 88702,
    graduated: 2854,
    aboutToGraduate: 29,
    rewardLaunches: 66999,
  },
  config: {
    graduationMarketCapUsd: 40000,
    aboutToGraduateMarketCapUsd: 32000,
    rewardLaunchesEnabled: true,
    pumpLaunchesEnabled: false,
    apiLaunchesEnabled: true,
    devBuysEnabled: true,
    paidLaunchesEnabled: false,
    launchLabEnabled: true,
  },
};

export const FIXTURE_PAIRS = [
  /** Quote asset for every launch. Captured 2026-09-20 from the live 521-pair list. */
  {
    mint: "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS",
    symbol: "ZEC",
    name: "Zcash",
    decimals: 8,
    logoUrl: "https://arweave.net/QSYqnmB7NYlB7n1R6rz935Y07dlRK0tIuKe2mof5Sho",
    category: "custom",
    categoryLabel: "Custom",
    tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
  {
    mint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    symbol: "SPYX",
    name: "SP500",
    decimals: 8,
    logoUrl: "/api/asset/quote-logo/XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    category: "xstock",
    categoryLabel: "xStock",
    tokenProgram: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
  {
    mint: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    symbol: "NVDAX",
    name: "NVIDIA",
    decimals: 8,
    logoUrl: "",
    category: "xstock",
    categoryLabel: "xStock",
    tokenProgram: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
  {
    mint: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
    symbol: "QQQX",
    name: "QQQ",
    decimals: 8,
    logoUrl: "",
    category: "xstock",
    categoryLabel: "xStock",
    tokenProgram: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
  {
    mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    symbol: "USDC",
    name: "USDC",
    decimals: 6,
    logoUrl: "",
    category: "currency",
    categoryLabel: "Currency",
    tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
  {
    mint: "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr",
    symbol: "EURC",
    name: "EURC",
    decimals: 6,
    logoUrl: "",
    category: "currency",
    categoryLabel: "Currency",
    tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
  {
    mint: "So11111111111111111111111111111111111111112",
    symbol: "SOL",
    name: "Wrapped SOL",
    decimals: 9,
    logoUrl: "",
    category: "solana",
    categoryLabel: "Solana",
    tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    launchable: true,
    symbolAmbiguous: false,
    launchLabReady: true,
  },
];


export const FIXTURE_PRICING = {
  quote: {
    mint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    symbol: "SPYX",
    decimals: 8,
    tokenProgram: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  },
  raise: {
    raw: "1212442937",
    units: 12.12442937,
    minimumRaw: "1",
    basis: "Sized so this launch is worth the same as the default 85 SOL raise.",
  },
  marketCap: {
    startUsd: 3060.05211319651,
    graduationUsd: 44963.87598247303,
  },
  curve: {
    programId: "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj",
    configId: "B7ctMMdGvy46Am56myTtzfkNzt9kWZVTNGM2BWrJ9adg",
    curveType: "ConstantCurve",
    migrateType: "cpmm",
    baseDecimals: 6,
    supply: "1000000000000000",
    totalSellA: "793100000000000",
    totalSupplyTokens: 1_000_000_000,
    vesting: { totalLockedAmount: "0", cliffPeriod: "0", unlockPeriod: "0" },
    derived: { virtualA: "1073025605839032", virtualB: "427933203" },
  },
  platform: {
    standard: "4E876qZTE9FJMrBzgVtBrSrzz2TLivB5Y5QXPjB4gZL7",
    reward: "6BwHHDg3u1854jC8PDLXvR4spTcLNaoBxLJNGC4nTESt",
  },
  curveRule: {
    standard: "QYZp1YzqEHU67ngXphF9LAkxkxWGvpWEv3rXh4yDbWA",
    reward: "7MNLMFMmFVhN9Z3sj51QZso28oD2Ta3zDPwNAmfrs2vk",
  },
  modes: {
    standard: { transferFee: null },
    reward: { transferFeeBps: [100, 300] },
  },
};
