/**
 * Shared ground truth for the Zcash publishing tests.
 *
 * Everything here is either a captured mainnet transaction or an official test
 * vector. Nothing is a value this repository produced, which is the point: the
 * serializer and the ZIP-244 digests are checked against bytes the network has
 * already accepted, not against themselves.
 */
import crypto from "node:crypto";
import { bytesToBigInt, encodePoint, generator, pointMul } from "../src/lib/protocol/secp256k1";
import { hexToBytes } from "../src/lib/zcash/transaction";
import type { StampPayload } from "../src/lib/zcash/inscription";
import stampFixture from "./fixtures/zcash/mainnet-stamp.json";
import vectorFixture from "./fixtures/zcash/zip-0244-vectors.json";
import katFixture from "./fixtures/zcash/blake2b-kat.json";

export const MAINNET = stampFixture;

/** The stamp the reference reveal carries, decoded in tests/inscription.test.ts. */
export const MAINNET_PAYLOAD: StampPayload = {
  p: "zsamtest",
  op: "mint",
  v: 1,
  mint: "3wbaQNg7QYnNV5izLUTqoGXeFDGj657T6HnbQmAap9Ye",
  burn: "RcxGYhJtLLmZAwhA1EeMqRCVEeC2edFSYb32Qjca1or4SzKNppf1nZS3czWL27Jf741rbZfPHUMp2PHLusG7x8M",
  amt: "1500000000000",
  to: "t1P2GcxGhzeM5tPk3r3JsGh1tEVArD4C2fB",
};

/** Read off the reference reveal's redeem script. */
export const MAINNET_REVEAL_PUBKEY = hexToBytes(
  "02965dda8783a3609eae684ca4eaae0881f58215ea19fcd57451c04e1bd27f0ae9",
);
export const MAINNET_COMMITMENT = hexToBytes(
  "5752a667013c9f75ab077768f298dc1df20c595e2efae59c5ddcadbfa0cd07b2",
);
export const MAINNET_REDEEM_SCRIPT_HEX =
  "2102965dda8783a3609eae684ca4eaae0881f58215ea19fcd57451c04e1bd27f0ae9ad205752a667013c9f75ab077768f298dc1df20c595e2efae59c5ddcadbfa0cd07b2757575757575757551";

/* ---------- ZIP-244 vectors ---------- */

export interface Zip244Vector {
  tx: string;
  /** Internal byte order, as the digest comes out. Reverse for display. */
  txid: string;
  auth_digest: string;
  amounts: number[];
  script_pubkeys: string[];
  transparent_input: number | null;
  sighash_shielded: string | null;
  sighash_all: string | null;
  sighash_none: string | null;
  sighash_single: string | null;
  sighash_all_anyone: string | null;
  sighash_none_anyone: string | null;
  sighash_single_anyone: string | null;
}

/**
 * The ZIP's own vectors, from zcash/zcash-test-vectors. The file is a header
 * row naming the columns followed by one array per transaction.
 */
export function zip244Vectors(): Zip244Vector[] {
  const rows = vectorFixture as unknown[];
  const names = (rows[1] as string[])[0]!.split(", ");
  return (rows.slice(2) as unknown[][]).map((row) => {
    const record: Record<string, unknown> = {};
    names.forEach((name, index) => (record[name] = row[index]));
    return record as unknown as Zip244Vector;
  });
}

/** The 256 keyed BLAKE2b-512 known-answer tests, with their shared key. */
export function blake2bKat(): { key: Uint8Array; hashes: string[] } {
  return { key: hexToBytes(katFixture.key), hashes: katFixture.hashes };
}

/* ---------- an independent signer ---------- */

export interface TestSigner {
  publicKey: Uint8Array;
  /** DER-encoded ECDSA signature over a raw 32-byte digest, no hash type byte. */
  sign(digest: Uint8Array): Uint8Array;
  /** The same key as OpenSSL derived it, for cross-checking scalar multiplication. */
  opensslPublicKey: Uint8Array;
}

/**
 * A signer for round-tripping the transaction builder.
 *
 * ECDSA over a bare 32-byte digest is not something Node will do: with a null
 * algorithm it still applies SHA-256, so `crypto.sign` cannot be handed a
 * ZIP-244 digest directly. The signing below therefore uses our own curve
 * arithmetic, and independence is recovered in two other places: the key is
 * generated by OpenSSL and `opensslPublicKey` lets a test confirm our scalar
 * multiplication lands on the same point, and the digests themselves are
 * checked against real mainnet signatures made by somebody else's wallet in
 * tests/zcash-zip244.test.ts. This signer proves the plumbing, not the maths.
 */
export function testSigner(seed?: string): TestSigner {
  const privateKey = seed
    ? privateKeyFromSeed(seed)
    : crypto.generateKeyPairSync("ec", { namedCurve: "secp256k1" }).privateKey;
  const jwk = privateKey.export({ format: "jwk" }) as { d: string; x: string; y: string };
  const scalar = bytesToBigInt(Buffer.from(jwk.d, "base64url"));
  const opensslPublicKey = encodePoint(
    {
      x: bytesToBigInt(Buffer.from(jwk.x, "base64url")),
      y: bytesToBigInt(Buffer.from(jwk.y, "base64url")),
    },
    true,
  );
  return {
    publicKey: encodePoint(pointMul(scalar, generator), true),
    opensslPublicKey,
    sign: (digest) => signDigest(digest, scalar),
  };
}

function modInverse(value: bigint, modulus: bigint): bigint {
  let [oldR, r] = [((value % modulus) + modulus) % modulus, modulus];
  let [oldS, s] = [1n, 0n];
  while (r !== 0n) {
    const q = oldR / r;
    [oldR, r] = [r, oldR - q * r];
    [oldS, s] = [s, oldS - q * s];
  }
  return ((oldS % modulus) + modulus) % modulus;
}

/**
 * Textbook ECDSA with a nonce derived from the key and the digest. Not RFC
 * 6979, and not constant time; it signs test digests with a throwaway key.
 * Low-S is enforced because Zcash, like Bitcoin, will not relay the other form.
 */
function signDigest(digest: Uint8Array, scalar: bigint): Uint8Array {
  const e = bytesToBigInt(digest) % SECP256K1_ORDER;
  for (let counter = 0; counter < 256; counter += 1) {
    const nonceBytes = crypto
      .createHash("sha256")
      .update(Buffer.concat([Buffer.from(digest), Buffer.from([counter]), bigIntToBuffer(scalar)]))
      .digest();
    const k = bytesToBigInt(nonceBytes) % SECP256K1_ORDER;
    if (k === 0n) continue;
    const point = pointMul(k, generator);
    if (!point) continue;
    const r = point.x % SECP256K1_ORDER;
    if (r === 0n) continue;
    let s = (modInverse(k, SECP256K1_ORDER) * (e + r * scalar)) % SECP256K1_ORDER;
    if (s === 0n) continue;
    if (s > SECP256K1_ORDER / 2n) s = SECP256K1_ORDER - s;
    return encodeDerSignature(r, s);
  }
  throw new Error("no usable nonce in 256 tries, which should not happen");
}

function bigIntToBuffer(value: bigint): Buffer {
  const hex = value.toString(16).padStart(64, "0");
  return Buffer.from(hex, "hex");
}

/** DER, with the leading zero byte an integer needs when its top bit is set. */
function encodeDerSignature(r: bigint, s: bigint): Uint8Array {
  const integer = (value: bigint): Buffer => {
    let bytes = bigIntToBuffer(value);
    let start = 0;
    while (start < bytes.length - 1 && bytes[start] === 0) start += 1;
    bytes = bytes.subarray(start);
    if (bytes[0]! & 0x80) bytes = Buffer.concat([Buffer.from([0]), bytes]);
    return Buffer.concat([Buffer.from([0x02, bytes.length]), bytes]);
  };
  const body = Buffer.concat([integer(r), integer(s)]);
  return Uint8Array.from(Buffer.concat([Buffer.from([0x30, body.length]), body]));
}

/**
 * A deterministic key, so a failing assertion is reproducible. The scalar is
 * the seed hashed and rejected if out of range, then wrapped in the SEC1
 * structure Node imports: INTEGER 1, the private key octets, and the secp256k1
 * curve OID 1.3.132.0.10.
 */
function privateKeyFromSeed(seed: string): crypto.KeyObject {
  let scalar = crypto.createHash("sha256").update(seed).digest();
  while (bytesToBigInt(scalar) === 0n || bytesToBigInt(scalar) >= SECP256K1_ORDER) {
    scalar = crypto.createHash("sha256").update(scalar).digest();
  }
  const der = Buffer.concat([
    Buffer.from("302e0201010420", "hex"),
    scalar,
    Buffer.from("a00706052b8104000a", "hex"),
  ]);
  return crypto.createPrivateKey({ key: der, format: "der", type: "sec1" });
}

const SECP256K1_ORDER = BigInt(
  "0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
);

/** Splits a DER ECDSA signature into its two scalars. */
export function parseDerSignature(der: Uint8Array): { r: bigint; s: bigint } {
  if (der[0] !== 0x30) throw new Error("not a DER sequence");
  if (der[2] !== 0x02) throw new Error("expected an integer for r");
  const rLength = der[3]!;
  const r = bytesToBigInt(der.subarray(4, 4 + rLength));
  if (der[4 + rLength] !== 0x02) throw new Error("expected an integer for s");
  const sLength = der[5 + rLength]!;
  const s = bytesToBigInt(der.subarray(6 + rLength, 6 + rLength + sLength));
  return { r, s };
}

/** The signature and redeem script a reveal scriptSig ends with. */
export function revealSignatureParts(scriptSig: Uint8Array): {
  signatureDer: Uint8Array;
  hashType: number;
  redeemScript: Uint8Array;
} {
  // Both are minimal pushes at the very end, so walking back from the tail is
  // unambiguous without re-parsing the envelope in front of them.
  const items: Uint8Array[] = [];
  let offset = 0;
  while (offset < scriptSig.length) {
    const opcode = scriptSig[offset]!;
    if (opcode >= 0x01 && opcode <= 0x4b) {
      items.push(scriptSig.subarray(offset + 1, offset + 1 + opcode));
      offset += 1 + opcode;
    } else if (opcode === 0x4c) {
      const length = scriptSig[offset + 1]!;
      items.push(scriptSig.subarray(offset + 2, offset + 2 + length));
      offset += 2 + length;
    } else if (opcode === 0x4d) {
      const length = scriptSig[offset + 1]! | (scriptSig[offset + 2]! << 8);
      items.push(scriptSig.subarray(offset + 3, offset + 3 + length));
      offset += 3 + length;
    } else {
      offset += 1;
    }
  }
  const redeemScript = items[items.length - 1]!;
  const withHashType = items[items.length - 2]!;
  return {
    signatureDer: withHashType.subarray(0, withHashType.length - 1),
    hashType: withHashType[withHashType.length - 1]!,
    redeemScript,
  };
}
